wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    framework: huggingface
    huggingface_version: 4.19.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1653836554
    t:
      1:
      - 1
      - 10
      - 11
      - 41
      - 48
      - 49
      - 55
      4: 3.9.12
      5: 0.12.17
      6: 4.19.2
      8:
      - 1
      - 5
